### ISSUE TITLE
TEMP_CTD_CNDC not in R25

### ISSUE THREAD

**Issue by BrianKingNOC** [nvs-vocabs/ArgoVocabs#114] opened 2023-10-09 10:38 UTC
@tcarval 

Hi Thierry

I noticed that TEMP_CTD_CNDC is not a sensor type available in R25, but it is required for RBR CTDs

**Comment by apswong** [comment] 2024-09-10 22:28
I requested this new SENSOR entry to R25 last year, but I can no longer find that Issue in Github, so I am glad this is raised again.  Yes, we need this new entry to R25, but the name of this new entry should be CTD_TEMP_CNDC (not TEMP_CTD_CNDC).

**Comment by apswong** [comment] 2024-09-11 00:27
@mscanderbeg kindly pointed out the link to the "old" Github Issue relating to this topic:

https://github.com/orgs/nvs-vocabs/projects/16/views/1?pane=issue&itemId=77354482

**Comment by danibodc** [comment] 2024-09-11 08:53
It looks like this has been created: https://vocab.nerc.ac.uk/collection/R25/current/CTD_TEMP_CNDC/

**Comment by tcarval** [comment] 2024-09-11 10:04
This old ticket is a duplicate of the closed https://github.com/nvs-vocabs/ArgoVocabs/issues/50.
The parameter CTD_TEMP_CNDC was registered in November 2023 on NVS (see https://vocab.nerc.ac.uk/collection/R25/current/CTD_TEMP_CNDC/)

So I close this ticket.

**Closed by tcarval** 2024-09-11 10:04 UTC
